domain:
  size: [1.0, 1.0, 2.0]  # [m]
  resolution: [32, 32, 64]
  periodicity: [true, true, false]

fluids:
  water:
    density: 1000.0  # [kg/m³]
    viscosity: 1.0e-3  # [Pa·s]
    surface_tension: 0.07  # [N/m]
    specific_heat: 4182.0  # [J/kg·K]
    thermal_conductivity: 0.6  # [W/m·K]
  
  air:
    density: 1.225  # [kg/m³]
    viscosity: 1.789e-5  # [Pa·s]
    surface_tension: 0.0  # [N/m]
    specific_heat: 1005.0  # [J/kg·K]
    thermal_conductivity: 0.024  # [W/m·K]

phase:
  epsilon: 0.01  # 界面厚さ
  mobility: 1.0  # 移動度
  surface_tension: 0.07  # [N/m]
  stabilization: 0.1  # 安定化係数

numerical:
  dt: 0.001  # [s]
  max_time: 1.0  # [s]
  cfl_number: 0.5
  tolerance: 1.0e-6
  max_iterations: 1000

output:
  save_interval: 0.01  # [s]
  output_dir: "output"
  save_format: "hdf5"
  visualization: true

gravity: 9.81  # [m/s²]