# Two-phase flow simulation configuration

# 物理パラメータ
physics:
  gravity: 9.81  # 重力加速度 [m/s²]
  surface_tension: 0.072  # 表面張力係数 [N/m]
  phases:
    water:
      density: 1000.0  # 密度 [kg/m³]
      viscosity: 1.0e-3  # 動粘性係数 [Pa·s]
      surface_tension: 0.07  # 表面張力係数 [N/m]
    nitrogen:
      density: 1.25  # 密度 [kg/m³]
      viscosity: 1.81e-5  # 動粘性係数 [Pa·s]
      surface_tension: 0.0  # 表面張力係数 [N/m]

# 計算領域の設定
domain:
  dimensions: [128, 128, 128]  # X, Y, Z方向のグリッドポイント数
  size: [1.0, 1.0, 1.0]  # X, Y, Z方向の物理的サイズ [m]

# 境界条件
boundary_conditions:
  x: 
    left: periodic
    right: periodic
  y: 
    bottom: periodic
    top: periodic
  z: 
    front: periodic
    back: periodic

# 初期条件
initial_conditions:
  # 初期界面の形状と配置
  background:
    phase: water  # 背景相を水に
    height_fraction: 0.80  # 領域の下80%を水で満たす
  
  objects:
    - type: sphere  # 窒素球
      phase: nitrogen
      center: [0.5, 0.5, 0.4]  # 中心座標 [x, y, z]
      radius: 0.2  # 半径

  # 初期速度場
  velocity:
    type: zero  # 速度をゼロに設定

# 数値スキーム
numerical:
  # シミュレーション制御
  max_time: 2.0  # 最大シミュレーション時間 [s]
  initial_dt: 0.001  # 初期時間刻み [s]
  save_interval: 0.1  # 結果の保存間隔 [s]

  # Level Set法のパラメータ
  level_set:
    epsilon: 1.5  # 界面の厚さパラメータ
    reinit_interval: 5  # 再初期化の間隔
    reinit_steps: 2  # 再初期化のステップ数

# 可視化設定
visualization:
  output_dir: "results/visualization"
  format: "png"
  dpi: 300
  dimensions: ["2D", "3D"]  # 可視化するディメンション
  
  # フィールド別の可視化設定
  fields:
    velocity:
      enabled: true
      plot_types: ["vector", "magnitude"]
    pressure:
      enabled: true
      plot_types: ["scalar", "contour"]
    levelset:
      enabled: true
      plot_types: ["interface", "contour"]
  
  # スライス設定
  slice:
    custom_planes:
      - axis: 2  # XY面
        name: "XY"
      - axis: 1  # XZ面
        name: "XZ"
      - axis: 0  # YZ面
        name: "YZ"

  # 3D可視化の設定（VTKやParaViewでの可視化）
  3d:
    enabled: true
    #method: ["vtk"]  # 複数の出力方法を指定可能
    method: ["vtk", "pyvista", "plotly"]  # 複数の出力方法を指定可能
    fields: 
      - velocity
      - pressure
      - levelset

# デバッグ設定
debug:
  level: "info"  # debug, info, warning, error
  save_fields: true  # デバッグ用のフィールドデータを保存
  check_divergence: true  # 速度発散のチェック
  plot_residuals: true  # 残差プロット
  profiling: false  # パフォーマンスプロファイリングを有効化