# Two-phase flow simulation configuration

# 物理パラメータ
physics:
  gravity: 9.81  # 重力加速度 [m/s²]
  surface_tension: 0.072  # 表面張力係数 [N/m]
  phases:
    water:
      density: 1000.0  # 密度 [kg/m³]
      viscosity: 1.0e-3  # 動粘性係数 [Pa·s]
      surface_tension: 0.07  # 表面張力係数 [N/m]
    nitrogen:
      density: 1.25  # 密度 [kg/m³]
      viscosity: 1.81e-5  # 動粘性係数 [Pa·s]
      surface_tension: 0.0  # 表面張力係数 [N/m]

# 計算領域の設定
domain:
  dimensions: [16, 16, 16]  # X, Y, Z方向のグリッドポイント数
  size: [0.1, 0.1, 0.1]  # X, Y, Z方向の物理的サイズ [m]

# 境界条件
boundary_conditions:
  x: 
    left: periodic
    right: periodic
  y: 
    bottom: periodic
    top: periodic
  z: 
    front: periodic
    back: periodic

# 初期条件
initial_conditions:
  background:
    phase: water
    height_fraction: 0.80

  objects:
    - type: sphere
      phase: nitrogen
      center: [0.5, 0.5, 0.4]
      radius: 0.3

  velocity:
    type: zero

# 数値スキーム
numerical:
  max_time: 2.0
  initial_dt: 0.001
  save_interval: 0.1

  level_set:
    epsilon: 1.5
    reinit_interval: 5
    reinit_steps: 2

# 可視化設定
visualization:
  output_dir: "results/visualization"
  format: "png"  # 出力フォーマット
  dpi: 300       # 解像度
  colormap: "viridis"  # デフォルトのカラーマップ
  show_colorbar: true  # カラーバーの表示
  show_axes: true      # 軸の表示
  show_grid: false     # グリッドの表示

  # カメラ設定（3D可視化用）
  camera:
    elevation: 30.0    # 仰角（度）
    azimuth: 45.0     # 方位角（度）
    distance: 10.0     # 視点距離
    focal_point: [0.5, 0.5, 0.5]  # 注視点

  # ベクトル場の設定
  vector_plot:
    density: 20        # ベクトル矢印の密度
    scale: 1.0         # ベクトル矢印のスケール
    width: 0.005       # 矢印の幅
    show_magnitude: true  # 大きさの表示
    streamlines: false    # 流線の表示
    n_streamlines: 50     # 流線の数

  # スカラー場の設定
  scalar_plot:
    interpolation: "nearest"  # 補間方法
    contour: false           # 等高線の表示
    n_contours: 10           # 等高線の数
    symmetric: false         # 対称なカラースケール

  # 3D表示の設定
  volume_plot:
    opacity: 0.7            # 不透明度
    slice_positions: [0.5, 0.5, 0.5]  # 各軸のデフォルト断面位置
    show_isosurfaces: true  # 等値面の表示
    n_isosurfaces: 5        # 等値面の数

  # Level Set場の設定
  interface_plot:
    color: "black"          # 界面の色
    width: 2.0              # 界面線の幅
    filled: true            # 領域の塗りつぶし
    phase_colors: ["lightblue", "white"]  # 各相の色

  # フィールドごとの可視化設定
  fields:
    velocity:
      enabled: true
      plot_types: ["vector", "magnitude"]
    pressure:
      enabled: true
      plot_types: ["scalar", "contour"]
    levelset:
      enabled: true
      plot_types: ["contour"]
      #plot_types: ["interface", "contour"]

# デバッグ設定
debug:
  level: "info"
  save_fields: true
  check_divergence: true
  plot_residuals: true
  profiling: false