# Two-phase flow simulation configuration

# 物理パラメータ
physics:
  gravity: 9.81  # 重力加速度 [m/s²]
  surface_tension: 0.072  # 表面張力係数 [N/m]

# 相の物性値
phases:
  water:
    density: 1000.0  # 密度 [kg/m³]
    viscosity: 1.0e-3  # 動粘性係数 [Pa·s]
    surface_tension: 0.07  # 表面張力係数 [N/m]
  nitrogen:
    density: 1.25  # 密度 [kg/m³]
    viscosity: 1.81e-5  # 動粘性係数 [Pa·s]
    surface_tension: 0.0  # 表面張力係数 [N/m]

# 計算領域の設定
domain:
  dimensions: [32, 32, 32]  # X, Y, Z方向のグリッドポイント数
  size: [1.0, 1.0, 1.0]  # X, Y, Z方向の物理的サイズ [m]

# 境界条件
boundary_conditions:
  x: 
    left: periodic
    right: periodic
  y: 
    front: periodic
    back: periodic
  z: 
    bottom: neumann
    top: neumann

# 初期条件
initial_conditions:
  background:
    phase: water
    height_fraction: 0.80

  objects:
    - type: sphere
      phase: nitrogen
      center: [0.5, 0.5, 0.4]
      radius: 0.2

  velocity:
    type: zero

# 数値スキーム
numerical:
  max_time: 2.0
  initial_dt: 0.001
  save_interval: 0.01

  level_set:
    epsilon: 1.0e-2
    reinit_interval: 5
    reinit_steps: 2

# 可視化設定
visualization:
  output_dir: "results/visualization"
  format: "png"  # 出力フォーマット
  dpi: 300       # 解像度
  colormap: "viridis"  # デフォルトのカラーマップ
  show_colorbar: true  # カラーバーの表示
  show_axes: true      # 軸の表示
  show_grid: false     # グリッドの表示

  # スライス位置と軸を明示的に指定
  slices:
    axes: 
      - "xy"   # XY面
      - "xz"   # XZ面
      - "yz"   # YZ面
    positions: 
      - 0.5    # 中央

  # 可視化する物理量を選択
  fields:
    velocity:
      enabled: false   # 速度場を可視化
    pressure:
      enabled: true   # 圧力場を可視化
    levelset:
      enabled: true

# デバッグ設定
debug:
  level: "info"
  save_fields: true
  check_divergence: true
  plot_residuals: true
  profiling: false