# 多相流体シミュレーション設定

physical:
  phases:
    - name: "water"
      density: 1000.0
      viscosity: 1.0e-3
      surface_tension_coefficient: 0.07  # 水の表面張力係数
    - name: "nitrogen"
      density: 1.225
      viscosity: 1.79e-5
      surface_tension_coefficient: 0.05  # 窒素の表面張力係数
  gravity: 9.81  # 重力加速度 [m/s²]
  surface_tension: 0.07  # デフォルトの表面張力係数 [N/m]

domain:
  Nx: 16   # x方向のグリッド数
  Ny: 16   # y方向のグリッド数
  Nz: 32   # z方向のグリッド数
  Lx: 1.0  # x方向の計算領域サイズ [m]
  Ly: 1.0  # y方向の計算領域サイズ [m]
  Lz: 2.0  # z方向の計算領域サイズ [m]

initial_condition:
  layers:
    - phase: "water" 
      z_range: [0.0, 1.4]  # 計算領域内に収める
    - phase: "nitrogen" 
      z_range: [1.4, 2.0]  # 計算領域内に収める
  spheres:
    - center: [0.5, 0.5, 0.4]
      radius: 0.2
      phase: "nitrogen"
    - center: [0.5, 0.5, 1.7]
      radius: 0.2
      phase: "water"
  initial_velocity: [0.0, 0.0, 0.0]  # 初期速度 [u, v, w]

numerical:
  dt: 0.001           # 初期時間刻み幅 [s]
  save_interval: 0.1  # データ保存間隔 [s]
  max_time: 1.0       # 最大計算時間 [s]
  max_steps: 1000     # 最大ステップ数
  cfl_factor: 0.5     # CFL条件の係数
  pressure_tolerance: 1e-6  # 圧力補正の収束判定
  velocity_tolerance: 1e-6  # 速度収束判定

boundary_conditions:
  x: periodic
  y: periodic
  z: neumann

visualization:
  phase_3d:
    elev: 30  # 相場の3D表示仰角 [度]
    azim: 45  # 相場の3D表示方位角 [度]
  velocity_3d:
    elev: 45  # 速度場の3D表示仰角 [度]
    azim: 60  # 速度場の3D表示方位角 [度]

logging:
  level: INFO
  output_dir: logs