physical:
  phases:
    - name: "water"
      density: 1000.0
      viscosity: 1.0e-3
    - name: "nitrogen"
      density: 1.225
      viscosity: 1.79e-5
  gravity: 9.81
  surface_tension: 0.07

domain:
  Nx: 32
  Ny: 32
  Nz: 64
  Lx: 1.0
  Ly: 1.0
  Lz: 2.0

initial_condition:
  layers:
    - phase: "water"
      z_range: [0.0, 1.5]
    - phase: "nitrogen" 
      z_range: [1.5, 2.0]
  spheres:
    - center: [0.5, 0.5, 0.4]
      radius: 0.2
      phase: "nitrogen"
    - center: [0.7, 0.3, 0.6]
      radius: 0.15
      phase: "nitrogen"
    - center: [0.3, 0.7, 1.7]
      radius: 0.18
      phase: "water"
  initial_velocity: [0.0, 0.0, 0.0]

numerical:
  dt: 0.001
  save_interval: 0.1
  max_time: 1.0